from alm.pra_calibration import FALL_TABLE, RATING_TO_CQS, RISE_TABLE, SPREAD_STRESS_TABLE, UNASSESSED_SPREAD_STRESS_TABLE, macaulay_duration, shock_curve_down, shock_curve_up, spread_stress_pct

from .correlation import aggregate_via_correlation
from .internal_model import InternalModelSCRResult, run_internal_model_scr, run_internal_model_scr_from_file
from .look_through import expand_look_through
from .standard_formula import (
    CONCENTRATION_RISK_FACTOR,
    CONCENTRATION_THRESHOLD_PCT,
    COUNTERPARTY_CASH_FACTOR,
    COUNTERPARTY_DERIVATIVE_FACTORS,
    COUNTERPARTY_REINSURANCE_FACTORS,
    CURRENCY_SHOCK,
    LONGEVITY_SHOCK_BEL_UPLIFT,
    MARKET_CORRELATION,
    MARKET_LIFE_CORRELATION,
    OPERATIONAL_FACTOR_OF_BEL,
    TOP_LEVEL_CORRELATION,
    ConcentrationScrResult,
    CounterpartyDefaultScrResult,
    CurrencyScrResult,
    FullStandardFormulaSCR,
    InterestRateScrResult,
    LongevityScrResult,
    MAPStandardFormulaSCR,
    OperationalScrResult,
    SpreadScrResult,
    compute_concentration_scr,
    compute_counterparty_default_scr,
    compute_currency_scr,
    compute_full_standard_formula_scr,
    compute_interest_rate_scr,
    compute_longevity_scr,
    compute_map_standard_formula_scr,
    compute_operational_scr,
    compute_spread_scr,
)

__all__ = [
    "aggregate_via_correlation",
    "FALL_TABLE",
    "RISE_TABLE",
    "shock_curve_down",
    "shock_curve_up",
    "InternalModelSCRResult",
    "run_internal_model_scr",
    "run_internal_model_scr_from_file",
    "expand_look_through",
    "CONCENTRATION_RISK_FACTOR",
    "CONCENTRATION_THRESHOLD_PCT",
    "COUNTERPARTY_CASH_FACTOR",
    "COUNTERPARTY_DERIVATIVE_FACTORS",
    "COUNTERPARTY_REINSURANCE_FACTORS",
    "CURRENCY_SHOCK",
    "LONGEVITY_SHOCK_BEL_UPLIFT",
    "MARKET_CORRELATION",
    "MARKET_LIFE_CORRELATION",
    "OPERATIONAL_FACTOR_OF_BEL",
    "RATING_TO_CQS",
    "SPREAD_STRESS_TABLE",
    "TOP_LEVEL_CORRELATION",
    "UNASSESSED_SPREAD_STRESS_TABLE",
    "ConcentrationScrResult",
    "CounterpartyDefaultScrResult",
    "CurrencyScrResult",
    "FullStandardFormulaSCR",
    "InterestRateScrResult",
    "LongevityScrResult",
    "MAPStandardFormulaSCR",
    "OperationalScrResult",
    "SpreadScrResult",
    "compute_concentration_scr",
    "compute_counterparty_default_scr",
    "compute_currency_scr",
    "compute_full_standard_formula_scr",
    "compute_interest_rate_scr",
    "compute_longevity_scr",
    "compute_map_standard_formula_scr",
    "compute_operational_scr",
    "compute_spread_scr",
    "macaulay_duration",
    "spread_stress_pct",
]
